### ISSUE TITLE
create_mnist.sh failed

### ISSUE THREAD

**Issue by andyyuan78** [Russell91/apollo#1]
ubgpu@ubgpu:~/github/apollo$ ./examples/mnist/create_mnist.sh
Creating lmdb...
./examples/mnist/create_mnist.sh: 16: ./examples/mnist/create_mnist.sh: build/examples/mnist/convert_mnist_data.bin: not found
./examples/mnist/create_mnist.sh: 18: ./examples/mnist/create_mnist.sh: build/examples/mnist/convert_mnist_data.bin: not found
Done.

ubgpu@ubgpu:~/github/apollo$ ./apollo/legacy.py --solver ./examples/mnist/lenet_solver.py --gpu 0
F0706 22:00:41.164203  3391 db.hpp:109] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
    @     0x7fe4cdd6c9fd  google::LogMessage::Fail()
    @     0x7fe4cdd6e89d  google::LogMessage::SendToLog()
    @     0x7fe4cdd6c5ec  google::LogMessage::Flush()
    @     0x7fe4cdd6f1be  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fe4cccd403e  caffe::db::LMDB::Open()
    @     0x7fe4ccc7ce65  caffe::DataLayer<>::DataLayerSetUp()
    @     0x7fe4ccc3ad49  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7fe4cccf657e  caffe::ApolloNet<>::ForwardLayer()
    @     0x7fe4cdfa0a66  __pyx_pw_6apollo_7_apollo_3Net_5forward_layer()
    @           0x499c7b  (unknown)
    @           0x499ef2  (unknown)
    @           0x4a090c  (unknown)
    @           0x49ab45  (unknown)
    @           0x499ef2  (unknown)
    @           0x4a1634  (unknown)
    @           0x44e4a5  (unknown)
    @           0x44ec9f  (unknown)
    @           0x44f904  (unknown)
    @     0x7fe4cf1e9ec5  (unknown)
    @           0x578c4e  (unknown)
Aborted (core dumped)
ubgpu@ubgpu:~/github/apollo$ 
ubgpu@ubgpu:~/github/apollo$

**Comment by Russell91** [comment]
Eh, sorry about this. I tried to remove all the MNIST files that weren't related to the simple example, but it looks like the convert_mnist_data.cpp file was necessary, and I wasn't able to detect the change because I hadn't run make clean. The following sequence should make things work:

    git pull origin master
    make
    ./examples/mnist/creat_mnist.sh
    # continue with the rest of he example
