### ISSUE TITLE
Missing directory

### ISSUE THREAD

**Issue by dmaliuk** [Russell91/apollo#2]
I tried running language_model.ipynb, but there is no ./data/language_model/get_lm.sh referred to in the notebook.

**Comment by Russell91** [comment]
Thanks for the notification. The download script is now at https://github.com/Russell91/apollo/blob/master/data/language_model/get_lm.sh

I had borrowed this from Caffe-NLP and the examples directory is in the .gitignore, so I hadn't picked this up.
