### ISSUE TITLE
How to handle when softmax outputs do not sum to 1.

### ISSUE THREAD

**Issue by icycandy** [Russell91/apollo#5]
I used the example data in `data/` directory, and run `char_model.py` without any modification.
the numpy version is 1.9.2
```bash
[candy@f22 apollo]$ md5sum data/language_model/vocab.pkl 
450c542ccb75a8fa9b2f86a39ee7db72  data/language_model/vocab.pkl
[candy@f22 apollo]$ md5sum data/char_model/reddit_ml.txt 
06f65f172f5d29377955b62a68062abe  data/char_model/reddit_ml.txt
```

```bash
[candy@f22 apollo]$ python examples/char_model.py 
2015-07-24 15:31:56,430 - INFO - Iteration 0: 5.53151462078
Traceback (most recent call last):
  File "examples/char_model.py", line 212, in <module>
    eval_performance(net)
  File "examples/char_model.py", line 139, in eval_performance
    eval_forward(eval_net)
  File "examples/char_model.py", line 165, in eval_forward
    output = softmax_choice(net.tops['softmax'].data)
  File "examples/char_model.py", line 145, in softmax_choice
    return np.random.choice(range(len(data.flatten())), p=data.flatten())
  File "mtrand.pyx", line 1094, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:10565)
ValueError: probabilities do not sum to 1
```

**Comment by nicodjimenez** [comment]
This is due to numpy having a low tolerance for probabilities not summing exactly to one.  It is not due to any errors in Apollo code (other than inevitable roundoff errors).  

There are two options.  The first one is to wrap the call in a try except block and catch the exception.  The other (perhaps easier) option is to replace calls to `softmax_choice` with `argmax_choice`, where:
```python
def argmax_choice(data):
    return np.argmax(data.flatten())
```

**Comment by icycandy** [comment]
How about normalize it before `np.random.choice`
```python
def softmax_choice(data):
    probs = np.array(data.flatten())
    probs /= probs.sum()
    return np.random.choice(range(len(probs)), p=probs)
```

**Comment by nicodjimenez** [comment]
weird, what happens if you `print probs.sum()` in this case?

**Comment by Russell91** [comment]
Given that this error occured with no modification of the file, I've hotfixed it here: https://github.com/Russell91/apollo/commit/903112c94d66e30d48e4ddc02a7965a0d5bfd488.

But it would be good to understand why this is failing and if there is a principled way to fix it. Not much thought has been put into how python will handle C++ returning NaNs or Infs, and it would be good to have a policy for what is supposed to happen in those cases.

**Comment by icycandy** [comment]
```pyhon
def softmax_choice(data):
    probs = np.array(data.flatten())
    print 'before normalize:'
    print probs.sum()
    print repr(probs.sum())
    probs /= probs.sum()
    print 'after normalize:'
    print probs.sum()
    print repr(probs.sum())
    sys.exit(0)
    return np.random.choice(range(len(probs)), p=probs)
```
gives the following result:

```bash
[olivertang@172.16.18.162 apollo]$ python examples/char_model.py 
2015-07-25 16:24:46,192 - INFO - Iteration 0: 5.53151462078
before normalize:
1.0
0.9999997
after normalize:
1.0
1.0
```

**Comment by Russell91** [comment]
So does dividing by the sum fix the issue or are there still other problems?

**Comment by icycandy** [comment]
Still the same problem `ValueError: probabilities do not sum to 1`.

**Comment by Russell91** [comment]
Okay, it seems that this is more of a bug with np.random.choice than anything else. The try except should do just fine.

**Comment by icycandy** [comment]
I report the bug to numpy, and they seems have fixed it. Before the next release of numpy, currently the workaround is converting `np.dtype` from `float32` to `float 64`
```python
def softmax_choice(data):
    probs = data.flatten().astype(np.float64)
    probs /= probs.sum()
    return np.random.choice(range(len(probs)), p=probs)
```

**Comment by Russell91** [comment]
Ah, nice. If you want, you can submit a pull request and get credit for the change. I'll change it myself in the next few days otherwise.

**Comment by icycandy** [comment]
PR submitted, this is the second PR in my whole life :)
