### ISSUE TITLE
import apollo Warning! ***HDF5 library version mismatched error***

### ISSUE THREAD

**Issue by mgarbade** [Russell91/apollo#7]
I followed your [installation instructions](http://apollo.deepmatter.io/) but when I try to run the example code provided there it crashes already on the second line when trying to import apollo:

    cd /path/to/apollo/examples/

--> start python 

    import apollo

It immediately outputs a lengthy warning stating that there was a problem with my hdf library version. 

    You can, at your own risk, disable this warning by setting the environment
    variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
    Setting it to 2 or higher will suppress the warning messages totally.
    Headers are 1.8.11, library is 1.8.9

Then it quits python. I tried compiling apollo with python and anaconda-python and got the same error. I tried to install a newer version of the hdf5 libraries but without success so far (also I fear to crash my system since I use hdf5 extensively in other programs (eg Matlab).
Is there another workaround or has anybody a good hint / has had the same problem?
I also don't know where to change that environment variable `HDF5_DISABLE_VERSION_CHECK`. In `.bashrc`, in python in some Makefile?
Thanks for your help

**Comment by Russell91** [comment]
Please add `export HDF5_DISABLE_VERSION_CHECK=1` to your ~.bashrc and then source it. It seems you have some nonstandard configuration where your HDF5 header files are from version 1.8.11 of the library, and the compiled binary is version 1.8.9 (not good!). But HDF5 is kind enough to let you proceed anyway by setting this flag. You may find the following relevant:

    https://github.com/ipython/ipython/issues/3031/

**Comment by mgarbade** [comment]
It worked. Thank you. 
It's still weird though. Because I'm quite sure I didn't mess around with my hdf5 libraries much apart from once installing "sudo apt-get install libhdf5-serial-dev".
