### ISSUE TITLE
UTF-8 support for char model

### ISSUE THREAD

**Issue by icycandy** [Russell91/apollo#9]
Currently, vocab size of char model is 256, don't support CJK characters. Does apollo support vocab size bigger than 256, eg. 8000 or 10000?

I modified the code to add UTF8 support, the vocab size is 8576. I trained a model on Chinese lyrics, but the results is weird. It outputs only few phrases and many newlines.
![1](https://cloud.githubusercontent.com/assets/724257/8928493/5fef9b84-3551-11e5-90a2-a346c8fb877f.png)

**Comment by Russell91** [comment]
Can you verify that you are using the most recent code? If not please pull in the changes and recompile. There was a bug discovered last week when training the Char-RNN on inputs of varying length (the original example dodged this for a complicated reason). Nets that had both a dynamic structure and reshaping of layers did not properly use the Blob API. I would bet that this is your issue.

**Comment by icycandy** [comment]
I checkout the newest code and tried again, this time it outputs only newlines, even the few phrases are gone. Maybe my code is wrong, I will check it carefully.

**Comment by Russell91** [comment]
Okay, you should also try printing the ordinal numbers rather than characters as well. The new code should be good, but if you show me the output as numbers I may be able to help.

**Comment by Russell91** [comment]
Do you have any update on whether you've been able to get it working? If the code is indeed not generalizing to your example, I'd like to prioritize finding out why. The whole point of that example is that people should be able to take it and do new things.

**Comment by icycandy** [comment]
Sorry for the late reply, I've been busy on other things these days.
I cloned the latest code today, and added utf-8 support for examples/char_model.py  (please refer to https://github.com/icycandy/apollo/commit/cfc0216befcbd9697390c2663c1b5a2b8affac9d)

The sampled output seems better than before, but still not good as expected.
Here are sampled output and the corresponding numbers. There are many `1` in the numbers, `1` is mapped to `\n` in vocab.

![1](https://cloud.githubusercontent.com/assets/724257/9056409/6fcb10dc-3ac5-11e5-800e-75b4ddba1d98.png)
![2](https://cloud.githubusercontent.com/assets/724257/9056408/6fa0b7a6-3ac5-11e5-9c51-a5ddd9c81b62.png)

**Comment by Russell91** [comment]
Okay, thanks for posting the code/data. We'll look into this.
